# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: scripts
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: git clone https://github.com/zhaoo/hexo-weapp-zhaoo.git
      
#     - run: cd /home/runner/work/hexo-little-program/hexo-little-program/hexo-weapp-zhaoo
    - run: ls
      working-directory: ./hexo-weapp-zhaoo/client
    #- run: npm install -g @tarojs/cli@3.2.1
    - run: npm run build:weapp
      working-directory: ./hexo-weapp-zhaoo/client
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          deploy_key: ${{ secrets.Token }}
          external_repository: hacker-jerry/hexo-little-program
          publish_branch: gh-pages
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
